# Generated by Django 6.0.2 on 2026-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Axborot xizmati', max_length=150, verbose_name='Tayyorlagan'),
            preserve_default=False,
        ),
    ]
