# Generated by Django 6.0.2 on 2026-03-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topbarsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Masalan: bi-bank', max_length=50)),
                ('count', models.CharField(help_text='Masalan: 770+', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Texnikum raqami',
                'verbose_name_plural': 'Texnikum raqamlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
