# Generated by Django 6.0.2 on 2026-03-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': "E'lon", 'verbose_name_plural': "E'lonlar"},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='order',
        ),
    ]
