# Generated by Django 6.0.2 on 2026-03-03 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_announcement_options_remove_announcement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
