# Generated by Django 6.0.2 on 2026-03-09 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announcement_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
