# Generated by Django 6.0.2 on 2026-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_announcement_published_at_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.CharField(default='Axborot xizmati', max_length=150, verbose_name='Tayyorlagan'),
            preserve_default=False,
        ),
    ]
