# Generated by Django 6.0.2 on 2026-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdirection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education/directions/'),
        ),
    ]
