# Generated by Django 6.0.3 on 2026-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education/assessment/'),
        ),
        migrations.AddField(
            model_name='control',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education/control/'),
        ),
    ]
