# Generated by Django 6.0.3 on 2026-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_assessment_image_control_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
