# Generated by Django 6.0.3 on 2026-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_control_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
