# Generated by Django 6.0.3 on 2026-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_assessment_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Baholash ', 'verbose_name_plural': 'Baholash '},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Nazorat ', 'verbose_name_plural': 'Nazorat '},
        ),
        migrations.AlterModelOptions(
            name='educationdirection',
            options={'ordering': ['name'], 'verbose_name': "Ta'lim yo'nalishi ", 'verbose_name_plural': "Ta'lim yo'nalishlari "},
        ),
        migrations.AlterModelOptions(
            name='educationprocess',
            options={'verbose_name': "O'quv jarayoni ", 'verbose_name_plural': "O'quv jarayoni "},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'Amaliyot ', 'verbose_name_plural': 'Amaliyot '},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
