# Generated by GPT-5.2 on 2026-04-07

from django.db import migrations, models
import django.db.models.deletion


def forwards_create_heads(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')
    DepartmentHead = apps.get_model('departments', 'DepartmentHead')

    for department in Department.objects.all().iterator():
        full_name = (department.head_name or '').strip() or "Noma'lum"
        head = DepartmentHead.objects.create(
            full_name=full_name,
            phone=getattr(department, 'phone', '') or '',
            email=getattr(department, 'email', '') or '',
        )
        department.head = head
        department.save(update_fields=['head'])


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kafedra mudiri',
                'verbose_name_plural': 'Kafedra mudirlari',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='department',
                to='departments.departmenthead',
            ),
        ),
        migrations.RunPython(forwards_create_heads, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='department',
            name='head_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='department',
                to='departments.departmenthead',
            ),
        ),
    ]

