# Generated by GPT-5.2 on 2026-04-08

from django.db import migrations, models


def forwards_split_full_name(apps, schema_editor):
    DepartmentHead = apps.get_model('departments', 'DepartmentHead')

    for head in DepartmentHead.objects.all().iterator():
        full_name = (getattr(head, 'full_name', '') or '').strip()
        if not full_name:
            head.last_name = "Noma'lum"
            head.first_name = "Noma'lum"
            head.middle_name = ''
            head.save(update_fields=['last_name', 'first_name', 'middle_name'])
            continue

        parts = [p for p in full_name.split(' ') if p]
        if len(parts) >= 2:
            head.last_name = parts[0]
            head.first_name = parts[1]
            head.middle_name = ' '.join(parts[2:]) if len(parts) > 2 else ''
        else:
            head.last_name = "Noma'lum"
            head.first_name = parts[0]
            head.middle_name = ''

        head.save(update_fields=['last_name', 'first_name', 'middle_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departmenthead_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='first_name',
            field=models.CharField(default="Noma'lum", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='last_name',
            field=models.CharField(default="Noma'lum", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='position',
            field=models.CharField(default='Kafedra mudiri', max_length=200),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='scientific_degree',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
        migrations.RunPython(forwards_split_full_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='departmenthead',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='departmenthead',
            name='created_at',
        ),
    ]
