# Generated by Django 6.0.3 on 2026-04-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_departmenthead_teacher_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenthead',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Kafedra mudiri', 'verbose_name_plural': 'Kafedra mudirlari'},
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='scientific_degree',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
